Add Instagram plugin
digitalocean/do-markdownit pull request #55
Opened 2023-03-21 15:40 UTC by MSzabi

## Type of Change

- **Markdown-It Plugins:** Instagram plugin

## What issue does this relate to?
N/A

### What should this PR do?
This introduces a new plugin with syntax for embedding posts from Instagram in Markdown. The syntax is [instagram <URL>], following the same pattern as many of our other embed plugins.

Like other embed plugins, it also supports optional flags after the URL, in this case for setting the alignment (left/center/right), and the width (between 326 and 550, per Instagram's docs).

### What are the acceptance criteria?
The new syntax works as expected, allowing the user to embed Instagram posts in Markdown content, optionally changing the post alignment or setting a custom width for the post.

2023-03-21 20:05 UTC, MattIPv4 requested changes

2023-03-21 20:05 UTC, MattIPv4 commented on rules/embeds/instagram.js
> +        if (currentLine.length < 13) return false; // [instagram a/p/b]
```suggestion
        if (currentLine.length < 13) return false; // [instagram a]
```

2023-03-22 08:51 UTC, MSzabi commented on rules/embeds/instagram.js
> +        if (currentLine.length < 13) return false; // [instagram a/p/b]
Changed.

2023-03-22 08:52 UTC, MSzabi commented on rules/embeds/instagram.js
> + * - Add any set of digits to set the width of the embed (in pixels, between 326 and 550, default is 540).
Yeah, initially I have defaulted from code to 540, then realized it's way too big, so I left the default that was coming from instagram. Forgot to update it here.
Done.

2023-03-22 08:52 UTC, MSzabi commented on styles/_instagram.scss
> +        .instagram-media{
Fixed.

2023-03-22 08:52 UTC, MSzabi commented on rules/embeds/instagram.js
> +            token.content = '<script async defer src="//www.instagram.com/embed.js" type="text/javascript"></script>\n';
Updated.

2023-03-22 09:50 UTC, MSzabi commented on rules/embeds/instagram.js
> + * <script async defer src="//www.instagram.com/embed.js" type="text/javascript"></script>
Introduced the alignment flag after the initial write-up and forgot to update it here. Should match now.

2023-03-22 14:52 UTC, MattIPv4 requested changes

2023-03-22 14:52 UTC, MattIPv4 commented on rules/embeds/instagram.js
> + * - Add any set of digits to set the width of the embed (in pixels, between 326 and 550, default is 326 not enforced here, but provided by Instagram's embed.js).
```suggestion
 * - Add any set of digits to set the width of the embed (in pixels, between 326 and 550, default is 326 as set by Instagram's embed.js).
```
Just cleaning up the wording here (please do the same to the README)

2023-03-23 13:27 UTC, MattIPv4 requested changes

2023-03-23 13:39 UTC, MSzabi commented on fixtures/full-input.md
> +- Pass any integer value (between 250 and 550) to set a custom width for the embed (e.g. `[instagram https://www.instagram.com/p/CkQuv3_LRgS 400]`)
Updated.

2023-03-23 13:39 UTC, MSzabi commented on fixtures/full-output.html
> +<li>Pass any integer value (between 250 and 550) to set a custom width for the embed (e.g. <code>[instagram https://www.instagram.com/p/CkQuv3_LRgS 400]</code>)</li>
Updated.

2023-03-23 13:39 UTC, MSzabi commented on fixtures/full-input.md
> +- Pass `caption` to include caption under the post (e.g. `[instagram https://www.instagram.com/p/CkQuv3_LRgS caption]`)
Me sorry for not adding it in the first place...
Fixed.

2023-03-23 13:46 UTC, MSzabi commented on rules/embeds/instagram.js
> +            token.content = '<script async defer src="https://www.instagram.com/embed.js" type="text/javascript"></script>\n';
Nice catch. Fixed.

2023-03-23 14:58 UTC, MattIPv4 approved these changes
LGTM

2023-03-23 15:36 UTC, merged