Update color palette to match new design system
digitalocean/do-markdownit pull request #83
Opened 2023-10-12 14:24 UTC by dbadea-heits

## Type of Change
- **SCSS Styling:** 
- Prism environment code blocks themes

## What issue does this relate to?

Update color themes for code blocks

### What should this PR do?
Updates color themes for code blocks

### What are the acceptance criteria?
Color themes for the code blocks are updated to use new color scheme

2023-10-16 13:39 UTC, MattIPv4 requested changes

2023-10-16 13:39 UTC, MattIPv4 commented on styles/_typography.scss
> +    background: linear-gradient($blue2, $blue2 ) bottom repeat-x;
```suggestion
    background: linear-gradient($blue2, $blue2) bottom repeat-x;
```

2023-10-16 13:39 UTC, MattIPv4 commented on styles/_theme.scss
> +$quternary: #F9FDF6 !default;
```suggestion
$quaternary: #F9FDF6 !default;
```

2023-10-16 13:39 UTC, MattIPv4 commented on styles/_theme.scss
> +$variable-dark: #B1E490 !default;
I think it might be worth prefixing these all with `code-` to make their usage clear?

2023-10-16 13:39 UTC, MattIPv4 commented on styles/digitalocean/_code_environments.scss
> +        @include code-block-theme($quternary, $text);
```suggestion
        @include code-block-theme($quaternary, $text);
```

2023-10-16 13:40 UTC, MattIPv4 commented
Please also add a line to `CHANGELOG.md` with the change being made here (`(minor) New design system colors` for example)

2023-10-16 14:16 UTC, MattIPv4 reviewed
👀 Changelog please

2023-10-16 14:38 UTC, MattIPv4 commented on CHANGELOG.md
> +- (minor) New design system colors
This should be in the unreleased changes section, not added to a release that has already been published

2023-10-16 20:01 UTC, MattIPv4 reviewed
Does the styling for the toolbar need updating to match the new design system?

2023-10-16 20:01 UTC, MattIPv4 commented on styles/_highlight.scss
> +            background: rgba($code-highlight-dark, 0.35);
Similarly here, this highlight is essentially invisible now?

2023-10-17 07:59 UTC, dbadea-heits commented on styles/_highlight.scss
> +    background: rgba($code-highlight, 0.35);
Thanks, i missed this, guessing the opacity makes no sense here. Also found some padding issues on highlights fixed those as well.

2023-10-17 12:08 UTC, dbadea-heits commented
We dont have a toolbar designed for this @MattIPv4

2023-10-17 15:35 UTC, MattIPv4 approved these changes
LGTM

2023-10-17 15:35 UTC, merged